### PR TITLE
fix(ci): Fix lint message on CI

### PR DESCRIPTION
**Pull request by mfornet**
move back to npm instead of yarn

### CODE REVIEW

**Review by sept-en — COMMENTED** [review]
I'm just curious, why do we need to move back to `npm`?

**Comment by mfornet** [comment]
> I'm just curious, why do we need to move back to `npm`?

Tbh it was using npm before the [last commit](https://github.com/aurora-is-near/aurora.js/commit/1ebcad6a45f1f000936654d0554fd78cfaf04f82), and I moved to yarn by mistake. I moved back to npm. no good reason, and I personally prefer yarn.

**Comment by pustovalov** [comment]
We can try to use [pnpm](https://pnpm.io/)

**Comment by spilin** [comment]
This repository is no longer maintained.

**Pull request closed without merging**
